# Generated by Django 5.0 on 2023-12-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='ModelJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('country', models.CharField(choices=[('Argentina', 'Argentina'), ('Spain', 'Spain'), ('USA', 'USA')], default='Argentina', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ManyToManyField(to='app.modelskill')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
            },
        ),
    ]
